spring.application.name=wolvesofdeliveryAPI

server.port=8080

spring.datasource.url=jdbc:postgresql://dpg-d76ljj7kijhs73bd9up0-a.oregon-postgres.render.com:5432/db_wolvesofdelivery?sslmode=require
spring.datasource.username=admin
spring.datasource.password=wIN7aXsK3q0Qw1vYDJnvyBsa4xqHdmPu

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.servlet.context-path=/wolvesofdeliveryAPI